In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import keras

Using TensorFlow backend.


In [2]:
# Importing the dataset
train = pd.read_csv('train.csv')
test = pd.read_csv('test_clean.csv')

In [3]:
test.shape

(289, 13)

In [4]:
train.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [5]:
train.dropna(inplace=True)

In [6]:
train.shape

(480, 13)

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [8]:
labelencoder1 = LabelEncoder()
train['Gender']= labelencoder1.fit_transform(train['Gender'])

In [9]:
labelencoder2 = LabelEncoder()
train['Married']= labelencoder2.fit_transform(train['Married'])

In [10]:
labelencoder3 = LabelEncoder()
train['Education']= labelencoder3.fit_transform(train['Education'])

In [11]:
labelencoder4 = LabelEncoder()
train['Self_Employed']= labelencoder4.fit_transform(train['Self_Employed'])

In [12]:
labelencoder5 = LabelEncoder()
train['Property_Area']= labelencoder5.fit_transform(train['Property_Area'])

In [13]:
labelencoder6 = LabelEncoder()
train['Loan_Status']= labelencoder6.fit_transform(train['Loan_Status'])

In [14]:
train.describe()

Gender     Married   Education  Self_Employed  ApplicantIncome  \
count  480.000000  480.000000  480.000000     480.000000       480.000000   
mean     0.820833    0.647917    0.202083       0.137500      5364.231250   
std      0.383892    0.478118    0.401973       0.344734      5668.251251   
min      0.000000    0.000000    0.000000       0.000000       150.000000   
25%      1.000000    0.000000    0.000000       0.000000      2898.750000   
50%      1.000000    1.000000    0.000000       0.000000      3859.000000   
75%      1.000000    1.000000    0.000000       0.000000      5852.500000   
max      1.000000    1.000000    1.000000       1.000000     81000.000000   

       CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
count         480.000000  480.000000        480.000000      480.000000   
mean         1581.093583  144.735417        342.050000        0.854167   
std          2617.692267   80.508164         65.212401        0.353307   
min             0.000000    9.000000         36.000000        0.000000   
25%             0.000000  100.000000        360.000000        1.000000   
50%          1084.500000  128.000000        360.000000        1.000000   
75%          2253.250000  170.000000        360.000000        1.000000   
max         33837.000000  600.000000        480.000000        1.000000   

       Property_Area  Loan_Status  
count     480.000000   480.000000  
mean        1.022917     0.691667  
std         0.776411     0.462287  
min         0.000000     0.000000  
25%         0.000000     0.000000  
50%         1.000000     1.000000  
75%         2.000000     1.000000  
max         2.000000     1.000000

In [15]:
train = pd.concat([train, pd.get_dummies(train['Property_Area'], prefix='property', drop_first=True)],axis=1)

In [16]:
train.drop(['Property_Area'], axis=1, inplace=True)

In [17]:
train.head()

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
1  LP001003       1        1          1          0              0   
2  LP001005       1        1          0          0              1   
3  LP001006       1        1          0          1              0   
4  LP001008       1        0          0          0              0   
5  LP001011       1        1          2          0              1   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   

   Credit_History  Loan_Status  property_1  property_2  
1             1.0            0           0           0  
2             1.0            1           0           1  
3             1.0            1           0           1  
4             1.0            1           0           1  
5             1.0            1           0           1

In [18]:
labels = train.Dependents.unique().tolist()

In [19]:
labels

['1', '0', '2', '3+']

In [20]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 480 entries, 1 to 613
Data columns (total 14 columns):
Loan_ID              480 non-null object
Gender               480 non-null int32
Married              480 non-null int32
Dependents           480 non-null object
Education            480 non-null int32
Self_Employed        480 non-null int32
ApplicantIncome      480 non-null int64
CoapplicantIncome    480 non-null float64
LoanAmount           480 non-null float64
Loan_Amount_Term     480 non-null float64
Credit_History       480 non-null float64
Loan_Status          480 non-null int32
property_1           480 non-null uint8
property_2           480 non-null uint8
dtypes: float64(4), int32(5), int64(1), object(2), uint8(2)
memory usage: 40.3+ KB


In [21]:
train['Dependents'] = train['Dependents'].replace(['3+'], 3)

In [22]:
labels = train.Dependents.unique().tolist()

In [23]:
labels

['1', '0', '2', 3]

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
target_name = 'Loan_Status'

In [26]:
X = train.drop('Loan_Status', axis=1)
y = train[target_name]

In [27]:
X = X.iloc[:, 1:12].values

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
y_train = train[0:480]['Loan_Status'].values
X_train = train[0:480].drop(['Loan_ID','Loan_Status'], axis=1).values
X_test  = test[0:367].drop(['Loan_ID'], axis=1).values

In [30]:
X_train

array([[1, 1, '1', ..., 1.0, 0, 0],
       [1, 1, '0', ..., 1.0, 0, 1],
       [1, 1, '0', ..., 1.0, 0, 1],
       ...,
       [1, 1, '1', ..., 1.0, 0, 1],
       [1, 1, '2', ..., 1.0, 0, 1],
       [0, 0, '0', ..., 0.0, 1, 0]], dtype=object)

In [31]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

D:\conda_env\dl_new\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\conda_env\dl_new\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [32]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [33]:
# Initialising the ANN
classifier = Sequential()

In [34]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))

In [35]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [36]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [37]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [38]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
480/480 [==============================] - 2s 5ms/step - loss: 0.6883 - acc: 0.6917
Epoch 2/100
480/480 [==============================] - 0s 405us/step - loss: 0.6724 - acc: 0.6917
Epoch 3/100
480/480 [==============================] - 0s 401us/step - loss: 0.6355 - acc: 0.6917
Epoch 4/100
480/480 [==============================] - 0s 478us/step - loss: 0.5807 - acc: 0.6917
Epoch 5/100
480/480 [==============================] - 0s 392us/step - loss: 0.5331 - acc: 0.7875
Epoch 6/100
480/480 [==============================] - 0s 367us/step - loss: 0.5080 - acc: 0.8083
Epoch 7/100
480/480 [==============================] - 0s 565us/step - loss: 0.4946 - acc: 0.8083
Epoch 8/100
480/480 [==============================] - 0s 440us/step - loss: 0.4837 - acc: 0.8125
Epoch 9/100
480/480 [==============================] - 0s 409us/step - loss: 0.4748 - acc: 0.8146
Epoch 10/100
480/480 [==============================] - 0s 362us/step - loss: 0.4675 - acc: 0.8146
Epoch 11/100
480/480 

480/480 [==============================] - 0s 447us/step - loss: 0.4223 - acc: 0.8354
Epoch 84/100
480/480 [==============================] - 0s 345us/step - loss: 0.4217 - acc: 0.8292
Epoch 85/100
480/480 [==============================] - 0s 324us/step - loss: 0.4215 - acc: 0.8313
Epoch 86/100
480/480 [==============================] - 0s 332us/step - loss: 0.4217 - acc: 0.8333
Epoch 87/100
480/480 [==============================] - 0s 347us/step - loss: 0.4210 - acc: 0.8312
Epoch 88/100
480/480 [==============================] - 0s 389us/step - loss: 0.4206 - acc: 0.8312
Epoch 89/100
480/480 [==============================] - 0s 382us/step - loss: 0.4202 - acc: 0.8312
Epoch 90/100
480/480 [==============================] - 0s 364us/step - loss: 0.4210 - acc: 0.8312
Epoch 91/100
480/480 [==============================] - 0s 378us/step - loss: 0.4201 - acc: 0.8333
Epoch 92/100
480/480 [==============================] - 0s 380us/step - loss: 0.4219 - acc: 0.8292
Epoch 93/100
480/480 [=

In [39]:
y_pred = classifier.predict(X_test)

In [40]:
y_pred

array([[0.8161325 ],
       [0.8411665 ],
       [0.8688414 ],
       [0.63744533],
       [0.6358804 ],
       [0.8256499 ],
       [0.05605446],
       [0.90917486],
       [0.6193546 ],
       [0.83630157],
       [0.81620127],
       [0.85360694],
       [0.92515296],
       [0.3293666 ],
       [0.88369256],
       [0.8408599 ],
       [0.5581758 ],
       [0.4729999 ],
       [0.5190561 ],
       [0.03576726],
       [0.5517987 ],
       [0.78229624],
       [0.8581078 ],
       [0.88554513],
       [0.91385794],
       [0.7925581 ],
       [0.84159786],
       [0.08397467],
       [0.83533883],
       [0.75009507],
       [0.6998283 ],
       [0.8096175 ],
       [0.687793  ],
       [0.94268703],
       [0.82208467],
       [0.71052706],
       [0.9126115 ],
       [0.84575593],
       [0.8485277 ],
       [0.93485445],
       [0.9072185 ],
       [0.75916845],
       [0.04501545],
       [0.4980412 ],
       [0.881561  ],
       [0.08742485],
       [0.8655198 ],
       [0.930

In [41]:
y_final = (y_pred > 0.5).astype(int).reshape(X_test.shape[0])

In [42]:
y_final

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [43]:
submission = pd.DataFrame({'Loan_ID':test['Loan_ID'],'Loan_Status':y_final})
submission.head()

Loan_ID  Loan_Status
0  LP001015            1
1  LP001022            1
2  LP001031            1
3  LP001051            1
4  LP001054            1

In [44]:
submission.to_csv('prediction.csv', index=False)